[tool.poetry]
name = "ehrconv"
version = "0.1.0"
description = ""
authors = ["Rafał Szuliński"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pandas= "^2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

